### ISSUE TITLE
panda/toyota.h: No such file or directory

### ISSUE THREAD

**Issue by rahulbhadani** [SafwanElmadani/can_to_ros#3]
I get the following error on doing catkin_make for the `can_to_ros` package. I have installed `libpanda` in my system so I am not sure why I am getting this error.

home/refulgent/catvehicle_ws/src/can_to_ros/src/vehicle_interface.cpp:37:10: fatal error: panda/toyota.h: No such file or directory
   37 | #include "panda/toyota.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
/home/refulgent/catvehicle_ws/src/can_to_ros/src/sendCommands.cpp:30:10: fatal error: panda/toyota.h: No such file or directory
   30 | #include "panda/toyota.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [can_to_ros/CMakeFiles/vehicle_interface.dir/build.make:82: can_to_ros/CMakeFiles/vehicle_interface.dir/src/vehicle_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1846: can_to_ros/CMakeFiles/vehicle_interface.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [can_to_ros/CMakeFiles/sendCommands.dir/build.make:82: can_to_ros/CMakeFiles/sendCommands.dir/src/sendCommands.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3210: can_to_ros/CMakeFiles/sendCommands.dir/all] Error 2
/home/refulgent/catvehicle_ws/src/can_to_ros/src/publish_libpanda.cpp:33:10: fatal error: panda.h: No such file or directory
   33 | #include <panda.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [can_to_ros/CMakeFiles/publish_libpanda.dir/build.make:82: can_to_ros/CMakeFiles/publish_libpanda.dir/src/publish_libpanda.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2228: can_to_ros/CMakeFiles/publish_libpanda.dir/all] Error 2
[ 98%] Built target can_to_ros_generate_messages_eus
[ 98%] Linking CXX shared library /home/refulgent/catvehicle_ws/devel/lib/libcatvehiclegazebo.so
[100%] Linking CXX shared library /home/refulgent/catvehicle_ws/devel/lib/libSteerPlugin.so
[100%] Built target catvehiclegazebo
[100%] Built target SteerPlugin
make: *** [Makefile:160: all] Error 2
Invoking "make -j12 -l12" failed

**Comment by selmadani** [comment]
Where did you install `libpanda` @rahulbhadani ? I cloned libpanda repo. in `/opt` and followed the build process.

**Comment by rahulbhadani** [comment]
@SafwanElmadani Cloning repo to `/opt`, building and installing it resolved the issue. Thanks for the suggestion.
I am closing the issue.
